import type { Position } from './types';

// Our own market valuations of real players, in tenths of £m (so 1750 = £175.0m).
//
// These are estimates generated by this model, not official or third-party transfer values:
//  1. Within each position, a player's quality is the blend of two within-position percentiles:
//     FPL price (a crowd-sourced demand signal) and the engine's overall rating.
//  2. That blended score is ranked within the position into a quality percentile Q from 0 (worst)
//     to 1 (best): the order is strict, ties break on overall, then price, then id.
//  3. A per-position convex curve turns Q into a value. The best player of each position gets the
//     position's ceiling; goalkeepers are capped below defenders, defenders below midfielders and
//     forwards, at equal quality.
// The pool a player is ranked against is the eligible pool (everyone except status "u"), so the
// valuation is a pure function of that pool, not of a single player. Not used by the simulation.
// Availability-based pricing (discounting injured or suspended players) is deliberately absent until
// injuries remove players from matches: before then it would hand out cheap strength.

export interface ValuationInput {
  id: string;
  position: Position;
  /** FPL price in tenths of £m: only ever used as a within-position percentile. */
  fplPrice: number;
  /** The engine's rounded overall rating. */
  overall: number;
}

export const MARKET_VALUE = {
  /** Weight of the FPL price percentile in the quality score; the engine overall gets the rest. */
  fplWeight: 0.4,
  /** Value curves: [quality percentile, £m], linear between knots and convex (slopes never fall). */
  curves: {
    GK: [
      [0, 1.54],
      [0.1, 1.54],
      [0.2, 1.59],
      [0.3, 1.66],
      [0.4, 1.81],
      [0.5, 2.11],
      [0.6, 2.76],
      [0.7, 4.14],
      [0.8, 8.65],
      [0.9, 16.29],
      [0.95, 24.06],
      [0.98, 39.84],
      [1, 54.79],
    ],
    DEF: [
      [0, 1.59],
      [0.1, 1.63],
      [0.2, 1.74],
      [0.3, 2.8],
      [0.4, 4.14],
      [0.5, 5.93],
      [0.6, 7.78],
      [0.7, 10.16],
      [0.8, 18.59],
      [0.9, 27.14],
      [0.95, 33.54],
      [0.98, 38.13],
      [1, 89.95],
    ],
    MID: [
      [0, 1.59],
      [0.1, 1.72],
      [0.2, 2.44],
      [0.3, 5.4],
      [0.4, 9.5],
      [0.5, 14.29],
      [0.6, 22.22],
      [0.7, 30.5],
      [0.8, 39.79],
      [0.9, 50.7],
      [0.95, 65.95],
      [0.98, 96.86],
      [1, 174.75],
    ],
    FWD: [
      [0, 1.58],
      [0.1, 1.81],
      [0.2, 2.27],
      [0.3, 3.03],
      [0.4, 5.02],
      [0.5, 7.44],
      [0.6, 12.98],
      [0.7, 19.04],
      [0.8, 34.73],
      [0.9, 54.06],
      [0.95, 77.16],
      [0.98, 130.61],
      [1, 174.99],
    ],
  } as Record<Position, readonly (readonly [number, number])[]>,
} as const;

const midRank = (values: readonly number[], x: number): number => {
  let below = 0;
  let equal = 0;
  for (const v of values) {
    if (v < x) below++;
    else if (v === x) equal++;
  }
  return (below + equal / 2) / values.length;
};

function interpolate(knots: readonly (readonly [number, number])[], q: number): number {
  const first = knots[0]!;
  if (q <= first[0]) return first[1];
  for (let i = 1; i < knots.length; i++) {
    const [q1, v1] = knots[i]!;
    if (q <= q1) {
      const [q0, v0] = knots[i - 1]!;
      return v0 + ((q - q0) / (q1 - q0)) * (v1 - v0);
    }
  }
  return knots[knots.length - 1]![1];
}

/** The value curve at quality `q`, with the cross-position caps (GK <= DEF <= MID, FWD). */
export function curveValue(position: Position, q: number): number {
  const { curves } = MARKET_VALUE;
  const own = interpolate(curves[position], q);
  if (position === 'FWD' || position === 'MID') return own;
  const defender = Math.min(
    interpolate(curves.DEF, q),
    interpolate(curves.MID, q),
    interpolate(curves.FWD, q),
  );
  return position === 'DEF' ? defender : Math.min(own, defender);
}

/** Round to realistic increments: 0.1m under £10m, 0.5m from £10m to £50m, £1m above. Tenths of £m. */
export function roundValue(millions: number): number {
  if (millions < 10) return Math.round(millions * 10);
  if (millions < 50) return Math.round(millions * 2) * 5;
  return Math.round(millions) * 10;
}

/** Quality percentile (0 = worst, 1 = best) of every player within their position. */
export function qualityPercentiles(pool: readonly ValuationInput[]): Map<string, number> {
  const result = new Map<string, number>();
  for (const position of ['GK', 'DEF', 'MID', 'FWD'] as const) {
    const group = pool.filter((p) => p.position === position);
    const prices = group.map((p) => p.fplPrice);
    const overalls = group.map((p) => p.overall);
    const w = MARKET_VALUE.fplWeight;
    const ranked = group
      .map((p) => ({
        p,
        score: w * midRank(prices, p.fplPrice) + (1 - w) * midRank(overalls, p.overall),
      }))
      .sort(
        (a, b) =>
          a.score - b.score ||
          a.p.overall - b.p.overall ||
          a.p.fplPrice - b.p.fplPrice ||
          a.p.id.localeCompare(b.p.id),
      );
    ranked.forEach(({ p }, index) =>
      result.set(p.id, group.length > 1 ? index / (group.length - 1) : 1),
    );
  }
  return result;
}

/** Market value of every player in the pool, in tenths of £m. Deterministic. */
export function marketValues(pool: readonly ValuationInput[]): Map<string, number> {
  const quality = qualityPercentiles(pool);
  const result = new Map<string, number>();
  for (const p of pool) {
    const base = curveValue(p.position, quality.get(p.id)!);
    result.set(p.id, roundValue(base));
  }
  return result;
}
