'use client';

import type { MatchEvent } from '@pl/engine';
import { useEffect, useMemo, useRef, useState } from 'react';
import { userDotColour } from '../match/lib/colours';
import { useHighlightsPitch } from '../match/components/useHighlightsPitch';
import {
  MATCH_BUDGET_MS,
  bannerAt,
  bannerEntriesOf,
  buildSchedule,
  formatClock,
  frameAt,
  scoreAt,
  type Banner,
  type LineupTeam,
} from '../match/lib/timeline';

/** The checked-in, unedited engine timeline generated by `generate-landing-match`. */
export interface LandingMatch {
  seed: number;
  home: LineupTeam;
  away: LineupTeam;
  score: { home: number; away: number };
  events: MatchEvent[];
}

const END_PAUSE_MS = 2_500;

export interface PlayerProps {
  reducedMotion: boolean;
  clubColour: string;
}

function Replay({ data, reducedMotion, clubColour }: PlayerProps & { data: LandingMatch }) {
  const { events, home, away } = data;
  const schedule = useMemo(() => buildSchedule(events, MATCH_BUDGET_MS), [events]);
  const bannerEntries = useMemo(() => bannerEntriesOf(schedule), [schedule]);
  const { wrapperRef, canvasRef, draw, reset } = useHighlightsPitch({
    allEvents: events,
    startIndex: 0,
    schedule,
    home,
    away,
    userSide: 'home',
    userColour: clubColour,
  });
  const [ui, setUi] = useState<{ revealed: number; banner: (Banner & { key: number }) | null }>({
    revealed: reducedMotion ? events.length : 0,
    banner: null,
  });
  const visibleRef = useRef(true);

  useEffect(() => {
    const wrapper = wrapperRef.current;
    if (!wrapper) return;
    if (reducedMotion) {
      // Static final frame: draw the end of the match once, and again whenever the size changes.
      const paint = () => {
        reset();
        draw(frameAt(schedule, schedule.totalMs), 1_000);
      };
      paint();
      const observer = new ResizeObserver(paint);
      observer.observe(wrapper);
      return () => observer.disconnect();
    }

    const intersection = new IntersectionObserver(([entry]) => {
      visibleRef.current = entry?.isIntersecting ?? true;
    });
    intersection.observe(wrapper);
    let raf = 0;
    let last = performance.now();
    let time = 0;
    const tick = (now: number) => {
      const dt = Math.min(64, now - last);
      last = now;
      if (visibleRef.current && !document.hidden) {
        time += dt;
        if (time > schedule.totalMs + END_PAUSE_MS) {
          time = 0;
          reset();
        }
        const clamped = Math.min(time, schedule.totalMs);
        const frame = frameAt(schedule, clamped);
        const banner = bannerAt(bannerEntries, clamped);
        setUi((previous) =>
          previous.revealed === frame.revealed && previous.banner?.key === banner?.key
            ? previous
            : { revealed: frame.revealed, banner },
        );
        draw(frame, dt);
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(raf);
      intersection.disconnect();
    };
  }, [bannerEntries, draw, reducedMotion, reset, schedule, wrapperRef]);

  const seen = events.slice(0, ui.revealed);
  const score = scoreAt(seen, home.id);
  const finalLabel = `Sample match: ${home.name} ${data.score.home}, ${away.name} ${data.score.away}`;

  return (
    <>
      <div className="hm-bug" aria-hidden="true">
        <span className="hm-tag">Sample match</span>
        <span className="hm-team">
          <i
            className="hm-swatch"
            style={{ background: userDotColour(clubColour) }}
            aria-hidden="true"
          />
          {home.name}
        </span>
        <strong className="hm-score">
          {score.home}–{score.away}
        </strong>
        <span className="hm-team">{away.name}</span>
        <time>{formatClock(seen.at(-1))}</time>
      </div>
      <div
        className="hm-pitch viewer-pitch"
        ref={wrapperRef}
        role="img"
        aria-label={`${finalLabel}. A muted highlights replay of a real engine match.`}
      >
        <canvas ref={canvasRef} />
        {ui.banner && !reducedMotion ? (
          <div className={`hm-banner ${ui.banner.tone}`} key={ui.banner.key} aria-hidden="true">
            <strong>{ui.banner.title}</strong>
            <span>{ui.banner.text}</span>
          </div>
        ) : null}
      </div>
    </>
  );
}

export function HeroMatchPlayer({ reducedMotion, clubColour }: PlayerProps) {
  const [data, setData] = useState<LandingMatch | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/landing-match.json')
      .then((response) => (response.ok ? (response.json() as Promise<LandingMatch>) : null))
      .then((json) => {
        if (!cancelled && json) setData(json);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, []);

  return data ? <Replay data={data} reducedMotion={reducedMotion} clubColour={clubColour} /> : null;
}
